CHOICES_ROLE = (
    ('A ESTUDANTE', 'A ESTUDANTE'),
    ('A EDUCADORA', 'A EDUCADORA'),
    ('A EMPREGADORA', 'A EMPREGADORA'),
    ('A MENTORA', 'A MENTORA'),
    ('A PROFISSIONAL', 'A PROFISSIONAL'),
    ('A ENTUSIASTA', 'A ENTUSIASTA'),
)
