CHOICES_ROLE = (
    ('A ESTUDANTE', 'A ESTUDANTE'),
    ('A PROGRAMADORA', 'A PROGRAMADORA'),
    ('A MENTORA', 'A MENTORA'),
    ('OS EDUCADORES', 'OS EDUCADORES'),
    ('A EMPREGADORA', 'A EMPREGADORA'),
    ('OS FACILITADORES', 'OS FACILITADORES'),
    ('OS APOIADORES', 'OS APOIADORES'),
)
