apiVersion: apps/v1
kind: Deployment
metadata:
  name: nisia
  namespace: production
  labels:
    app: nisia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nisia
  template:
    metadata:
      labels:
        app: nisia
    spec:
      containers:
      - name: nisia
        image: docker.mastertech.com.br/nisia:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: nisia
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: nisia
  namespace: production
  labels:
    app: nisia
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nisia
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nisia
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
        charset utf-8;
        charset_types *;
spec:
  tls:
  - hosts:
    - nisia.mastertech.com.br
    secretName: mastertech-com-br
  rules:
  - host: nisia.mastertech.com.br
    http:
      paths:
      - path: /
        backend:
          serviceName: nisia
          servicePort: 80

