apiVersion: apps/v1
kind: Deployment
metadata:
  name: nisia
  namespace: staging
  labels:
    app: nisia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nisia
  template:
    metadata:
      labels:
        app: nisia
    spec:
      containers:
      - name: nisia
        image: docker.mastertech.com.br/nisia:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 50m
            memory: 128Mi
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            host:
            scheme: HTTP
            path: /
            port: 80
        livenessProbe:
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
          httpGet:
            host:
            scheme: HTTP
            path: /
            port: 80
        envFrom:
        - secretRef:
            name: nisia
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: nisia
  namespace: staging
  labels:
    app: nisia
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nisia
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nisia
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        charset utf-8;
        charset_types *;
spec:
  rules:
  - host: nisia.homolog.mastertech.com.br
    http:
      paths:
      - backend:
          serviceName: nisia
          servicePort: 80
        path: /

