# Generated by Django 2.2.3 on 2019-07-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
                ('role', models.CharField(choices=[('A ESTUDANTE', 'A ESTUDANTE'), ('A EDUCADORA', 'A EDUCADORA'), ('A EMPREGADORA', 'A EMPREGADORA'), ('A MENTORA', 'A MENTORA'), ('A PROFISSIONAL', 'A PROFISSIONAL')], default='A ESTUDANTE', max_length=50, verbose_name='Qual o papel que você desempenha hoje?')),
                ('story', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Registrados',
            },
        ),
    ]
