# Generated by Django 2.2.3 on 2020-01-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nisia_cadastro', '0002_registered_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='role',
            field=models.CharField(choices=[('A ESTUDANTE', 'A ESTUDANTE'), ('A PROGRAMADORA', 'A PROGRAMADORA'), ('A MENTORA', 'A MENTORA'), ('OS EDUCADORES', 'OS EDUCADORES'), ('A EMPREGADORA', 'A EMPREGADORA'), ('OS FACILITADORES', 'OS FACILITADORES'), ('OS APOIADORES', 'OS APOIADORES')], default='A ESTUDANTE', max_length=50, verbose_name='Qual o papel que você desempenha hoje?'),
        ),
    ]
