# Generated by Django 2.2.3 on 2020-01-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nisia_cadastro', '0003_auto_20200130_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
